### ISSUE TITLE
Edit FreeMC (MCSHosting)

### ISSUE THREAD

**Issue by Qubopp** [summerhoax/summerhoax.github.io#79]
Add this brilliant screenshot 
https://cdn.discordapp.com/attachments/607317247245156379/608769203595509799/unknown.png

**Comment by Daxorinator** [comment]
Badly edited, out of context, nothing that changes their status on Summerhoax, seems like a bad attempt to shit on them that nobody asked for. Sorry Solid.

Voting to close.

**Comment by DamonOnYT** [comment]
> Badly edited, out of context, nothing that changes their status on Summerhoax, seems like a bad attempt to shit on them that nobody asked for. Sorry Solid.
> 
> Voting to close.

Agreed.

**Comment by Daxorinator** [comment]
@Ethereal739 Close please.
