### ISSUE TITLE
Add panel.rapidmc.xyz

### ISSUE THREAD

**Issue by AshleyHunter01** [summerhoax/summerhoax.github.io#93]
![0EA59041-A51D-4A43-A49E-5679C525A5EB](https://user-images.githubusercontent.com/38188828/66516848-e60e2400-ead9-11e9-9b8a-47676e7b6dcd.jpeg)
Refused to give me atleast have my money back, used contabo vps from NickE, not even a registered company
![5B0A80F2-30F0-4F53-9687-554A63EE998E](https://user-images.githubusercontent.com/38188828/66516751-b52def00-ead9-11e9-8d55-3030cef57709.jpeg)
![Uploading C684AEBF-BC0A-4000-8D46-CD83986F49AA.jpeg…]()

**Comment by Ethereal739** [comment]
Why are you asking to get your money back?

**Comment by lazarsn** [comment]
Hmmm

**Comment by AshleyHunter01** [comment]
I paid for ram and he couldn’t even keep his nodes, i only asked for half of what i payed and he refuses to even pay half back. He also lost and corrupted my files twice causing alot of issues for my mc server

**Comment by Ethereal739** [comment]
Do you have proof of this?

**Comment by AshleyHunter01** [comment]
![E6189C0B-8A75-4EA0-BBEA-6ED232BB0943](https://user-images.githubusercontent.com/38188828/66517332-dfcc7780-eada-11e9-807f-34a85df267d6.jpeg)
![E4E33487-4907-45CB-9B3F-9FDB90A36241](https://user-images.githubusercontent.com/38188828/66517333-dfcc7780-eada-11e9-917d-e1533a1ecf74.jpeg)
![A30EA80B-5205-4DCF-9878-AC4B8A210C33](https://user-images.githubusercontent.com/38188828/66517334-dfcc7780-eada-11e9-9a86-e77841aac66b.jpeg)

**Comment by AshleyHunter01** [comment]
I legit only asked for half my cash yet he refuses to give it back they are not even registered

**Comment by AshleyHunter01** [comment]
He is now deleting messages in dms, if he had nothing to hide why delete your messages

**Comment by Ethereal739** [comment]
I have seen no proof of the server blowing up though, even if he deleted the messages could you show me a screenshot of what's left?

**Comment by AshleyHunter01** [comment]
![44C0AEBA-041F-44FC-9218-52ECA30C39DB](https://user-images.githubusercontent.com/38188828/66517710-8dd82180-eadb-11e9-92e2-070ded02e3d8.png)
![4487285E-8069-40A7-B96C-502A28080E52](https://user-images.githubusercontent.com/38188828/66517711-8dd82180-eadb-11e9-99af-285fed488d61.png)
![5331C7EC-1788-44F3-AFEC-EF4EE96071D5](https://user-images.githubusercontent.com/38188828/66517713-8dd82180-eadb-11e9-91e2-ff3323c96c29.png)
![F22FE556-0514-445C-9FDE-EBB90C0A169B](https://user-images.githubusercontent.com/38188828/66517714-8dd82180-eadb-11e9-8203-6006286bda26.png)
![8946BD90-A2CE-46CF-ADD1-71A8BEA15206](https://user-images.githubusercontent.com/38188828/66517716-8e70b800-eadb-11e9-86f8-6e073d1358de.png)
![C781F3FB-9510-45A4-AD0C-4901C13AF131](https://user-images.githubusercontent.com/38188828/66517718-8e70b800-eadb-11e9-9a55-a75a4705f7e8.png)

**Comment by AshleyHunter01** [comment]
These are what i manage to get

**Comment by AshleyHunter01** [comment]
I was nice enough to buy them a .host and they never claimed it I offered to give him it if he gives me my cash but he refuses

**Comment by Ethereal739** [comment]
Alright please make a pull request and I will merge
